name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the full repo is checked out for accurate analysis

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Comment out cache steps to rule out caching issues
      # - name: Cache SonarQube packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.sonar/cache
      #     key: ${{ runner.os }}-sonar
      #     restore-keys: ${{ runner.os }}-sonar

      # - name: Cache Maven packages
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2

      - name: Verify Environment Variables
        run: |
          echo "SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}"
          echo "SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}"
          echo "SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}"

      - name: Build and Analyze with SonarCloud
        env:
          #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=GJanos_mvn-sonar-gitaction \
          -Dsonar.organization=gjanos \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectName="mvn-sonar-gitaction"
